apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vcluster
spec:
  interval: 5m
  releaseName: test-vcluster
  chart:
    spec:
      chart: vcluster
      version: 0.15.0
      sourceRef:
        kind: HelmRepository
        name: loft
        namespace: veecluster
      interval: 1m
  values:
    replicaCount: 2